version: '3.4'

services:
  app:
    build: .
    entrypoint: sh -c 'while sleep 3600; do :; done'
    working_dir: /usr/src/app
    volumes:
      - "../source/:/usr/src/app"
    ports:
      - "$PORT"
    environment:
      - DNSDOCK_ALIAS=$DNSDOCK_ALIAS
      - VIRTUAL_PORT=$PORT
      - VIRTUAL_HOST=$DNSDOCK_ALIAS

  